### ISSUE TITLE
can't get samples working

### ISSUE THREAD

**Issue by jacky-ttt** [realm/electron-react-samples#1]
I cloned the repository and follow the instructions in README.md to run it. 
1. `npm install`
2. `npm start` 

Below error occurs in the electron console. That is caused by not finding the platform specific build of realm. The realm native module is not compiled in the process. Please advise on how to perform the module build. 
```
Uncaught Error: Cannot find module '/Users/jackytsang/Downloads/electron-react-samples-master/reactive-datagrid/node_modules/realm/compiled/electron-v1.8_darwin_x64/realm.node'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/Users/jackytsang/Downloads/electron-react-samples-master/reactive-datagrid…ctron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jackytsang/Downloads/electron-react-samples-master/reactive-datagrid/node_modules/realm/lib/index.js:102:28)
    at Object.<anonymous> (/Users/jackytsang/Downloads/electron-react-samples-master/reactive-datagrid/node_modules/realm/lib/index.js:133:3)
    at Module._compile (module.js:569:30)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jackytsang/Downloads/electron-react-samples-master/reactive-datagrid/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (module.js:503:32)
```

I am developing on 
* macOS 10.13.4
* npm 5.6.0
* node 8.11.1

**Comment by cbeninati** [comment]
Same issue.

It's apparently looking for a Node module in `electron-v1.8_darwin_x64` while the actual path in `node_modules` is: `electron-react-samples/reactive-datagrid/node_modules/realm/compiled/electron-v1.7_darwin_x64/realm.node`.


<img width="811" alt="screen shot 2018-05-01 at 4 21 24 pm" src="https://user-images.githubusercontent.com/1027918/39496476-d6a8da18-4d5b-11e8-959d-8aedeaf77fb5.png">

As a test, I renamed that `electron-v1.7_darwin_x64` to `electron-v1.8_darwin_x64` but got a 'different Node version' error.

<img width="1053" alt="screen shot 2018-05-01 at 4 24 29 pm" src="https://user-images.githubusercontent.com/1027918/39496556-2a3519e4-4d5c-11e8-8542-2d468d90e8c1.png">
